### ISSUE TITLE
MessageProducer send throws java.lang.UnsupportedOperationException

### ISSUE THREAD

**Issue by ghost** [dfedorov-solace/solace-samples-amqp-jms1#16]
MessageProducer send(topic, ...) throws:

Exception in thread "main" java.lang.UnsupportedOperationException: Using this method is not supported on producers created with an explicit Destination.
	at org.apache.qpid.jms.JmsMessageProducer.send(JmsMessageProducer.java:187)
	at com.solace.samples.TopicPublisher.run(TopicPublisher.java:75)
	at com.solace.samples.TopicPublisher.main(TopicPublisher.java:94)

It happens in BasicReplier, QueueProducer and TopicPublisher

**Comment by ghost** [comment]
The error was introduced by reviewer's request during integration with the existing SolaceSample code as a cosmetic change for consistency with the previously published code.
